[platformio]
boards_dir = ../boards

[env:tpager_launcher]
platform = espressif32@6.7.0
board = lilygo_t_pager
framework = arduino

board_build.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.partitions = ../partitions/rspager_16mb_dual.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = dio_qspi

build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -I../src/platform
    -I../src

build_unflags =
    -std=gnu++11

lib_deps =
    lovyan03/LovyanGFX@~1.1.16

monitor_speed = 115200
upload_speed = 460800
upload_protocol = esptool
upload_flags = --no-stub
